name = "deepseek-worker"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"

# Production environment
[env.production]
name = "deepseek-worker"
# DEEPSEEK_API_KEY should be set as a secret using:
# wrangler secret put DEEPSEEK_API_KEY --env production

# Development environment (optional, inherits from main config)
[env.dev]
name = "deepseek-worker-dev"
# For development, secrets can be set using:
# wrangler secret put DEEPSEEK_API_KEY --env dev
